server:
  port: 8080
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
#Mybatis配置
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
#上传文件大小的配置
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 10000MB
#阿里云oss配置
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:

#Spring事务日志管理
logging:
  level:
    org.springframework.support.JdbcTransactionManager: debug